name: GitLeaks

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest

    container:
      image: zricethezav/gitleaks
      volumes:
        - ${{ github.workspace }}:/path

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /path

      - name: Detect
        run: |
          gitleaks detect --source='/path' --report-format=json --report-path='/path/gitleaks-report.json'

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gitleaks-report-${{ github.sha }}
          path: /path/gitleaks-report.json
